from __future__ import annotations

from datetime import datetime, timezone
import math
from pathlib import Path
import re
from typing import List

from .model import DataType, WiringError, WiringProject


def _format_parameter(data_type: DataType, value: str) -> str:
    value = str(value).strip()
    if not value or re.search(r"\s|#", value):
        raise WiringError("Invalid parameter value: %r" % value)
    if data_type == DataType.BIT:
        normalized = value.lower()
        if normalized in ("true", "yes", "on"):
            return "1"
        if normalized in ("false", "no", "off"):
            return "0"
        if normalized not in ("0", "1"):
            raise WiringError("BIT parameter must be 0 or 1: %s" % value)
    elif data_type in (DataType.S32, DataType.U32):
        try:
            number = int(value, 0)
        except ValueError as exc:
            raise WiringError("Invalid integer parameter: %s" % value) from exc
        minimum = 0 if data_type == DataType.U32 else -(2 ** 31)
        maximum = (2 ** 32 - 1) if data_type == DataType.U32 else (2 ** 31 - 1)
        if not minimum <= number <= maximum:
            raise WiringError("Parameter is outside the %s range: %s" % (data_type.value, value))
    elif data_type == DataType.FLOAT:
        try:
            number = float(value)
        except ValueError as exc:
            raise WiringError("Invalid floating-point parameter: %s" % value) from exc
        if not math.isfinite(number):
            raise WiringError("Floating-point parameter must be finite: %s" % value)
    return value


def generate_hal(project: WiringProject, include_timestamp: bool = False) -> str:
    errors = project.validate()
    if errors:
        raise WiringError("Cannot generate invalid wiring:\n- " + "\n- ".join(errors))

    lines: List[str] = [
        "# Generated by cia402-wiring-gui. Manual changes may be overwritten.",
    ]
    if include_timestamp:
        lines.append("# Generated at %s" % datetime.now(timezone.utc).isoformat())

    parameters = [
        parameter
        for node in project.nodes.values()
        if node.active
        for parameter in node.parameters.values()
    ]
    if parameters:
        lines.extend(("", "# Component parameters"))
        for parameter in sorted(parameters, key=lambda item: item.full_name):
            lines.append(
                "setp %-42s %s"
                % (parameter.full_name, _format_parameter(parameter.data_type, parameter.value))
            )

    active_signals = project.active_signals()
    if active_signals:
        lines.extend(("", "# Signal connections"))
        for signal in active_signals:
            if len(signal.destinations) == 1:
                lines.append(
                    "net %-28s %-42s => %s"
                    % (signal.name, signal.source, signal.destinations[0])
                )
            else:
                lines.append("net %-28s %s \\" % (signal.name, signal.source))
                for index, destination in enumerate(signal.destinations):
                    continuation = " \\" if index < len(signal.destinations) - 1 else ""
                    lines.append("    => %s%s" % (destination, continuation))

    lines.append("")
    return "\n".join(lines)


def write_hal(project: WiringProject, path: Path) -> None:
    with Path(path).open("w", encoding="utf-8", newline="\n") as stream:
        stream.write(generate_hal(project))
